(function(){var g;function C(c,d){c.X=d;c.prototype=Object.create(d.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}})}
(function(c){c.btoa||(c.btoa=function(c){c=String(c);for(var f,h,k=0,e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",l="";c.charAt(k|0)||(e="=",k%1);l+=e.charAt(63&f>>8-k%1*8)){h=c.charCodeAt(k+=.75);if(255<h)throw Error();f=f<<8|h}return l});c.atob||(c.atob=function(c){c=String(c).replace(/=+$/,"");if(1==c.length%4)throw Error();for(var f=0,h,k,e=0,l="";k=c.charAt(e++);~k&&(h=f%4?64*h+k:k,f++%4)?l+=String.fromCharCode(255&h>>(-2*f&6)):0)k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(k);
return l})})(window);var F="function"!==typeof Object.create?"~":!1;function aa(c,d,f){this.t=c;this.context=d;this.U=f||!1}function I(){}g=I.prototype;g.s=void 0;g.V=function(c,d){var f=F?F+c:c,f=this.s&&this.s[f];if(d)return!!f;if(!f)return[];if(f.t)return[f.t];for(var h=0,k=f.length,e=Array(k);h<k;h++)e[h]=f[h].t;return e};
g.r=function(c,d,f,h,k,e){var l=F?F+c:c;if(!this.s||!this.s[l])return!1;var l=this.s[l],n=arguments.length,q,m;if("function"===typeof l.t){l.U&&this.Rb(c,l.t,void 0,!0);switch(n){case 1:return l.t.call(l.context),!0;case 2:return l.t.call(l.context,d),!0;case 3:return l.t.call(l.context,d,f),!0;case 4:return l.t.call(l.context,d,f,h),!0;case 5:return l.t.call(l.context,d,f,h,k),!0;case 6:return l.t.call(l.context,d,f,h,k,e),!0}m=1;for(q=Array(n-1);m<n;m++)q[m-1]=arguments[m];l.t.apply(l.context,q)}else{var p=
l.length,u;for(m=0;m<p;m++)switch(l[m].U&&this.Rb(c,l[m].t,void 0,!0),n){case 1:l[m].t.call(l[m].context);break;case 2:l[m].t.call(l[m].context,d);break;case 3:l[m].t.call(l[m].context,d,f);break;default:if(!q)for(u=1,q=Array(n-1);u<n;u++)q[u-1]=arguments[u];l[m].t.apply(l[m].context,q)}}return!0};g.j=function(c,d,f){d=new aa(d,f||this);c=F?F+c:c;this.s||(this.s=F?{}:Object.create(null));this.s[c]?this.s[c].t?this.s[c]=[this.s[c],d]:this.s[c].push(d):this.s[c]=d;return this};
g.U=function(c,d,f){d=new aa(d,f||this,!0);c=F?F+c:c;this.s||(this.s=F?{}:Object.create(null));this.s[c]?this.s[c].t?this.s[c]=[this.s[c],d]:this.s[c].push(d):this.s[c]=d;return this};g.Rb=function(c,d,f,h){c=F?F+c:c;if(!this.s||!this.s[c])return this;var k=this.s[c],e=[];if(d)if(k.t)(k.t!==d||h&&!k.U||f&&k.context!==f)&&e.push(k);else for(var l=0,n=k.length;l<n;l++)(k[l].t!==d||h&&!k[l].U||f&&k[l].context!==f)&&e.push(k[l]);e.length?this.s[c]=1===e.length?e[0]:e:delete this.s[c];return this};
g.Ga=I.prototype.Rb;var ba=0;function ca(){ba=(1103515245*ba+12345)%2147483648;return ba/2147483648}Math.Pe=function(c){return c*Math.PI/180};Math.Ne=function(c){return 180*c/Math.PI};
function O(c){function d(c){c=c-(k-e);if(!(0>c)){for(var p=128;p<c;)p+=128;f(k+p)}}function f(c){var p=q;h(new ArrayBuffer(c));p&&q.set(p,0)}function h(c){l=c;n=new DataView(l);q=new Uint8Array(l);k=n.byteLength}var k=0,e=0,l=null,n=null,q=null;c instanceof ArrayBuffer?h(c):f(c||64);this.data=function(){return new Uint8Array(l,0,e)};this.c=function(){return k-e};this.l=function(){return e};this.v=function(c,p,u,f){if(null!=f)return n[c](f,p);d(u);n[c](e,p);e+=u};this.y=function(c,p,u){if(null!=u)return n[c](u);
if(this.c()<p)throw new RangeError("avail: "+this.c()+", read:"+p);c=n[c](e);e+=p;return c};this.Zb=function(c,p,u){p=p||0;if(!u||u>c.length-p)u=c.length-p;d(u);q.set(new Uint8Array(c,p,u),e);e+=u};this.jd=function(c){var p,e;p=p||0;e=e||c.byteLength;c instanceof ArrayBuffer||(p+=c.byteOffset,c=c.buffer);this.sa(e);this.Zb(c,p,e)};this.Sc=function(){var c=n.getUint16(e);e+=2;var p;p=e+c;if(q.slice)p=q.slice(e,p);else if(q.subarray)p=q.subarray(e,p);else throw Error("not way to slice data");e+=c;return p};
this.Tc=function(){return this.y("getInt16",2)};this.ya=function(){return this.y("getUint8",1)};this.pa=function(){return this.y("getUint16",2)};this.te=function(){return this.y("getUint32",4)};this.$b=function(c){this.v("setInt16",c,2,void 0)};this.ja=function(c){this.v("setUint8",c,1,void 0)};this.sa=function(c){this.v("setUint16",c,2,void 0)};this.He=function(c){this.v("setUint32",c,4,void 0)}}function da(){}da.prototype=Object.create(I.prototype);da.prototype.constructor=da;var Q=new da;
Q.Qa=!1;Q.Ha=13;window.jgdv="v"+Q.Ha;Q.ld=function(){var c=Q.A;Q.pb=!0;c.requestFullscreen?c.requestFullscreen():c.webkitRequestFullscreen?c.webkitRequestFullscreen():c.mozRequestFullScreen?c.mozRequestFullScreen():c.msRequestFullscreen&&c.msRequestFullscreen()};Q.exitFullscreen=function(){Q.pb=!1;document.exitFullscreen?document.exitFullscreen():document.webkitExitFullscreen?document.webkitExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen&&document.msExitFullscreen()};
Q.log=function(c){return{e:window.jigidi_log?window.jigidi_log("debug",c):function(){},ie:window.jigidi_log?window.jigidi_log("info",c):function(){},g:window.jigidi_log?window.jigidi_log("error",c):function(){},fd:window.jigidi_log?window.jigidi_log("stat",c):function(){},Uc:function(){return this}}};Q.d={};Q.d.La=1;Q.d.$=2;Q.d.C=3;Q.d.O=4;Q.d.N=5;Q.d.Q=6;Q.Ra="state_change";Q.Q="error_event";Q.i=Q.d.La;var R=Q.log("jigidi");
Q.ob=function(c){function d(c,h){if(c&&h&&c instanceof Object&&h instanceof Object){for(var k in h)c[k]=d(c[k],h[k]);return c}return h}Q.n=d(Q.n,c)};
Q.md=function(c){Q.ob(c);R.e("init");var d=Q.A=Q.n.dom;Q.mb="#ba9";var f=document.createElement("canvas");f.width=Math.round(d.clientWidth*(window.devicePixelRatio||window.screen.deviceXDPI/window.screen.logicalXDPI||1));f.height=Math.round(d.clientHeight*(window.devicePixelRatio||window.screen.$d/window.screen.logicalYDPI||1));f.style.width="100%";f.style.height="100%";d.appendChild(f);window.addEventListener("resize",function(){R.e("resize: "+d.clientWidth+", "+d.clientHeight);f.width=d.clientWidth*
(window.devicePixelRatio||window.screen.deviceXDPI/window.screen.logicalXDPI||1);f.height=d.clientHeight*(window.devicePixelRatio||window.screen.$d/window.screen.logicalYDPI||1);Q.k.ia(Math.round(f.width/2),Math.round(f.height/2));Q.k.bd(f.width,f.height);Q.k.fa();Q.ga();Q.n.resize&&Q.n.resize(f.width,f.height)},!1);Q.canvas=f;Q.k=new Q.q.sc;Q.k.ia(Math.round(f.width/2),Math.round(f.height/2));Q.k.bd(f.width,f.height);R.e("create InteractionManager");new ea(Q.canvas,Q.k);Q.da=new fa;Q.k.Ma(Q.da);
Q.context=f.getContext("2d",{Jd:!1});Q.f.add(Q.ga);Q.ca=new ga;Q.ca.n();Q.ca.g(function(c){R.g("Config error: "+c);Q.i=Q.d.Q;Q.r(Q.Ra,Q.i);Q.r(Q.Q,c)});ha()};Q.td=function(){Q.B.Zd()};Q.vd=function(c){Q.P(Q.d.Q);Q.r(Q.Q,c)};Q.nd=function(){R.e("config loaded");Q.B=new ia(Q.ca.B);R.e("Loading progress: "+Q.B);Q.B.j(ja,Q.sd);Q.B.j(ka,Q.pd);Q.B.j(la,Q.rd)};Q.qd=function(){R.e("connected to GameServer");0<Q.T&&R.fd("reconnect");Q.T=0};Q.za=function(){Q.B.za()};
Q.rd=function(c){R.e("disconnected from GameServer - "+c.cb);Q.T||R.fd("disconnect_"+c);var d;(d=!c.za&&!Q.T)||(R.e("Jigidi._reconnecting = "+Q.T),Q.T||(Q.T=(new Date).getTime()+1E4),(new Date).getTime()>Q.T?d=!1:(setTimeout(Q.za,200+Math.round(2E3*Math.random())),d=!0),d=!d);if(d){d="";switch(c.cb){case "one-connection-only":d="You were disconnected.<br><br>Another connection was established to this game.";break;case "close-abnormal":d="Connection to Jigidi was lost.";break;default:d="You were disconnected. ("+
c.cb+")"}Q.vd(d)}};Q.pd=function(c){S&&new ma(c)};Q.sd=function(c,d){R.e("Progress state change: "+d);switch(d){case na:Q.qd();Q.i==Q.d.La&&Q.qb();break;case oa:Q.i==Q.d.La&&Q.qb()}};Q.P=function(c){Q.i!=c&&(Q.i=c,R.e("Jigidi state-change: "+Q.i),Q.r(Q.Ra,Q.i))};
Q.qb=function(){var c=Q.ca,d=Q.B.Qd();Q.i!=Q.d.La?R.g("setupBoard called in state: "+Q.i):(d||(d=Q.ca,d=new Q.u.D({ta:d.size.a,ua:d.size.b,oa:d.x.width,na:d.x.height}),d.se(),d=d.Yd()),pa(),Q.c=new Q.kd(c.x,c.size.a,c.size.b,d),Q.c.j(Q.Fa.Wa,function(c,d){Q.n.fnBuildProgress&&Q.n.fnBuildProgress(c/d)}),Q.c.j(Q.Fa.Va,function(c,d){Q.n.fnBuildDone&&Q.n.fnBuildDone(c,d)}),Q.c.j(Q.Fa.N,function(){Q.n.fnComplete&&Q.n.fnComplete()}),Q.c.R.j(Q.u.D.lc,function(){Q.n.fnJoin&&Q.n.fnJoin(Q.c.R.Qc(),Q.c.R.re())}),
Q.c.U(Q.Fa.Va,Q.wd),Q.c.R.j(Q.u.D.$a,function(c){switch(c){case Q.u.D.$:Q.P(Q.d.$);break;case Q.u.D.C:Q.P(Q.d.C);break;case Q.u.D.O:Q.P(Q.d.O);break;case Q.u.D.N:Q.P(Q.d.N)}}))};Q.wd=function(){Q.B.Pd();R.e("add board: "+Q.c+" below: "+Q.da);Q.k.Na(Q.c,Q.da);R.e("setup-complete")};Q.ud=function(c){Q.mb=c;Q.k.fa()};
Q.ga=function(){var c=Q.k,d=Q.context,f=Q.canvas;if(c.Ib){c.Ib=!1;var h=new Q.q.xd,k=Q.k.Sb?null:new Q.q.pc;Q.n.preRender&&Q.n.preRender();c.Rc(h,k);d.save();k&&!Q.Qa&&(k.trim(),d.beginPath(),d.rect(k.a,k.b,k.width,k.height),d.clip());d.fillStyle=Q.mb;d.fillRect(0,0,f.width,f.height);c.hb(d,k);Q.n.postRender&&Q.n.postRender();d.restore()}};window.jigidi_init=Q.md;
function qa(c,d,f,h,k){function e(c,e,m,d,t,l){var f=1==t||2==t?-d:d;d=2==t||3==t?-d:d;var h=0==t%2?p:u;l&&0==t%2&&(f*=-1);l&&1==t%2&&(d*=-1);c.lineTo(e+h[0].h*f,m+h[0].m*d);for(t=1;t<h.length;t+=2)c.quadraticCurveTo(e+h[t].h*f,m+h[t].m*d,e+h[t+1].h*f,m+h[t+1].m*d)}var l=Q.log("cutter"),n=Math.floor(f/c),q=Math.floor(h/d),m=[],p=[{h:0,m:-75},{h:0,m:-20},{h:50,m:-45},{h:100,m:-75},{h:130,m:-50},{h:150,m:-35},{h:150,m:0},{h:150,m:35},{h:130,m:50},{h:100,m:75},{h:50,m:45},{h:0,m:20},{h:0,m:75}],u=[];
for(f=0;f<p.length;++f)u.push({h:p[f].m,m:p[f].h});ba=parseInt(k)%2147483648;this.dd=function(){return n};this.ed=function(){return q};this.Hb=function(c,p,d){var u=m[2*p+0][2*d+0],t=m[2*p+2][2*d+0],h=m[2*p+2][2*d+2],f=m[2*p+0][2*d+2],l=m[2*p+1][2*d+0],k=m[2*p+2][2*d+1],A=m[2*p+1][2*d+2],x=m[2*p+0][2*d+1],H=(n+q)/200;p=-(p+.5)*n;d=-(d+.5)*q;c.moveTo(p+u.a,d+u.b);0!=l.Z&&e(c,p+l.a,d+l.b,.22*H,3,1==l.Z);c.lineTo(p+t.a,d+t.b);0!=k.Z&&e(c,p+k.a,d+k.b,.22*H,0,1==k.Z);c.lineTo(p+h.a,d+h.b);0!=A.Z&&e(c,
p+A.a,d+A.b,.22*H,1,1!=A.Z);c.lineTo(p+f.a,d+f.b);0!=x.Z&&e(c,p+x.a,d+x.b,.22*H,2,1!=x.Z);c.lineTo(p+u.a,d+u.b)};this.qe=function(c,p){var d={Mc:0,h:function(c,p){this.Mc||(this.ac=this.bc=c,this.cc=this.dc=p,this.Mc=1);this.ac=Math.min(this.ac,c);this.cc=Math.min(this.cc,p);this.bc=Math.max(this.bc,c);this.dc=Math.max(this.dc,p)}};d.moveTo=d.lineTo=d.h;d.quadraticCurveTo=function(c,p,d,e){this.h(c,p);this.h(d,e)};this.Hb(d,c,p);c=Math.floor(d.ac);p=Math.floor(d.cc);return{a:c,b:p,width:Math.ceil(d.bc)-
c,height:Math.ceil(d.dc)-p}};(function(){l.e("CUTTER: setupGrid, seed: "+ba);for(var p=0;p<2*c+1;++p){for(var e=[],u=0;u<2*d+1;++u){var h={a:-1,b:-1,Z:0,toString:function(){return this.a+","+this.b+":"+this.Z}};e.push(h);var t=!1,f=!1;if(0==p||0==u)t=!0;if(p==2*c||u==2*d)t=!0;0==p%2&&0==u%2&&(f=!0);if(!t||f)h.a=p*n*.5,h.b=u*q*.5,t||(h.a+=(ca()-.5)*n*.08,h.b+=(ca()-.5)*q*.08,f||(1==p%2&&(h.a+=(ca()-.5)*n*.1),1==u%2&&(h.b+=(ca()-.5)*q*.1),h.Z=.5>ca()?1:2))}m.push(e)}})()}Q.q={};
(function(c){function d(){function c(p){e[p]||(e[p]={V:[],U:[]});return e[p]}function d(c,p){for(var e=0;e<c.length;e++)c[e].apply(null,p)}var e={};this.j=function(d,e){c(d).V.push(e);return this};this.Ga=function(c,p){if(e[c]){var d=e[c],m=d.V,u=m.indexOf(p);0>u||m.splice(u,1);d=d.U;m=d.indexOf(p);0>m||d.splice(m,1);return this}};this.U=function(d,e){c(d).U.push(e);return this};this.r=function(c,p,m,h){if(e[c]){var f=e[c],l=Array.prototype.slice.call(arguments,1);d(f.V,l);d(f.U,l);f.U=[]}}}function f(c,
d){this.a=c||0;this.b=d||0}function h(c,d,e,m){this.a=c||0;this.b=d||0;this.width=e||0;this.height=m||0}function k(){this.h=1;this.I=this.m=0;this.J=1;this.H=this.G=0}function e(){this.Pa=null;this.c=[];var c=new f,d=1,e=new k;this.f=!1;this.l=function(){return c};this.ia=function(d,e){c.a=d;c.b=e;this.nb()};this.scale=function(){return d};this.Vb=function(c){d=c;this.nb()};this.n=function(){this.f&&(e.c(),e.scale(d,d),e.d(c.a,c.b),this.f=!1);return e}}function l(){function c(d,e){d.k!=e&&(d.k=e,
d.k&&d.zc(),d.ka(function(d){c(d,e)}))}l.X.apply(this);d.apply(this);this.ba=!1;this.bb=!0;var e=null,m=1;this.k=null;this.Jd=function(){return m};this.Ub=function(c){m=c;this.fa()};this.fb=function(c){return this.Ta.Ud(c)?!0:!1};this.Da=function(c){c&&(e=new h(c.a,c.b,c.width,c.height));return e};this.nb=function(){l.X.prototype.nb.call(this);this.k&&this.k.ra()};this.Ma=function(c){this.Na(c)};this.Na=function(d,e){l.X.prototype.Na.call(this,d,e);this.k&&(c(d,this.k),this.k&&this.k.ra())};this.removeChild=
function(d){l.X.prototype.removeChild.call(this,d);this.k&&this.k.ra();c(d,null)};this.Wc=function(){l.X.prototype.Wc.call(this);this.ka(function(d){c(d,null)});this.k&&this.k.ra()};this.zc=function(){};this.Xb=function(c){return this.ha.Ac(c)};this.Ee=function(c){return this.ha.apply(c)};this.ha=this.Ta=this.d=null;var f=!1;this.fa=function(){f=!0;this.ka(function(c){c.fa()});this.k&&this.k.ra()};this.Rc=function(c,p){var d=this.d;this.ha=c.wa();this.ha.Kd(this.n());if(e){var m=e.d();this.ha.Nd(m);
this.d=h.c(m)}else this.d=null;this.Ta=this.d?this.d.wa():new h;this.ka(function(c){c.Rc(this.ha,p);this.Ta.Yb(c.Ta)}.bind(this));!f&&d&&d.Kc(this.d)||(f=!1,p&&(d&&p.Yb(d),this.d&&p.Yb(this.d)))};this.hb=function(c,p,d){d=d||0;var e=!1;this.d&&(e=p?p.je(this.d):!0);this.ga&&e&&(c.save(),e=this.ha,c.setTransform(e.h,e.m,e.I,e.J,e.G,e.H),c.globalAlpha=m,this.ga(c),c.restore());this.ka(function(e){e.hb(c,p,d+1)}.bind(this));if(Q.Qa){c.save();e=this.ha;c.setTransform(e.h,e.m,e.I,e.J,e.G,e.H);c.beginPath();
c.arc(0,0,10,0,2*Math.PI,!1);c.fillStyle="#f00";c.fill();c.restore();e=this.Ta;c.strokeStyle="#00f";c.strokeRect(e.a,e.b,e.width,e.height);c.font="12px Arial";c.fillStyle="#000";var h=this.constructor.name;h||(h=this.toString());c.fillText(d+":"+h,e.a+5,e.b+15)}}}function n(){n.X.apply(this);this.x=null;this.ze=function(c){this.x=c;var d=new h;d.width=c.width;d.height=c.height;d.a=-Math.round(d.width/2);d.b=-Math.round(d.height/2);this.Da(d)};this.ga=function(c){for(var d=this.Da(),e=0;1>e;e++)c.drawImage(this.x,
d.a,d.b)}}function q(){q.X.apply(this);this.ba=!0;this.k=this;this.Ib=!1;this.Sb=!0;this.size={width:0,height:0};this.toString=function(){return"Stage"};this.bd=function(c,p){this.size.width=c;this.size.height=p;this.r(q.oc,this)};this.fa=function(){this.ra();this.Sb=!0};var c=this.hb;this.hb=function(d,e,m){c.call(this,d,e,m);this.Sb=!1};this.ra=function(){this.Ib=!0};this.fb=function(){return!0}}Q.log("gfx");f.prototype.toString=function(){return this.a+","+this.b};f.prototype.wa=function(){return new f(this.a,
this.b)};f.prototype.Kc=function(c){return c.a===this.a&&c.b===this.b};f.prototype.set=function(c,d){this.a=c||0;this.b=d||(0!==d?this.a:0)};f.prototype.scale=function(c,d){return new f(this.a*c,this.b*d)};f.prototype.c=function(c){return(this.a-c.a)*(this.a-c.a)+(this.b-c.b)*(this.b-c.b)};f.prototype.Oa=function(c){return Math.sqrt(this.c(c))};f.prototype.add=function(c){this.a+=c.a;this.b+=c.b};f.prototype.sub=function(c){this.a-=c.a;this.b-=c.b};h.prototype.toString=function(){var c=[],d;for(d in{a:0,
b:0,width:0,height:0})c.push(Math.round(10*this[d])/10);return"{"+c.join(", ")+"}"};h.prototype.wa=function(){return new h(this.a,this.b,this.width,this.height)};h.prototype.c=function(c){this.a=c.a;this.b=c.b;this.width=c.width;this.height=c.height};h.prototype.d=function(){return[new f(this.a,this.b),new f(this.a+this.width,this.b),new f(this.a+this.width,this.b+this.height),new f(this.a,this.b+this.height)]};h.c=function(c){var d,e,m,f;d=m=c[0].a;e=f=c[0].b;for(var l=1,t=c.length;l<t;l++){var k=
c[l].a,n=c[l].b;d=Math.min(d,k);e=Math.min(e,n);m=Math.max(m,k);f=Math.max(f,n)}return new h(d,e,m-d,f-e)};h.prototype.Kc=function(c){return this.a==c.a&&this.b==c.b&&this.width==c.width&&this.height==c.height};h.prototype.Yb=function(c){if(0!=c.width||0!=c.height)if(0==this.width&&0==this.height)this.c(c);else{var d=Math.min(this.a,c.a),e=Math.max(this.a+this.width,c.a+c.width),m=Math.min(this.b,c.b);c=Math.max(this.b+this.height,c.b+c.height);this.a=d;this.b=m;this.width=e-d;this.height=c-m}};h.prototype.je=
function(c){return this.a+this.width<c.a||this.a>c.a+c.width||this.b+this.height<c.b||this.b>c.b+c.height?!1:!0};h.prototype.Ud=function(c){return 0>=this.width||0>=this.height||c.a<this.a||c.a>this.a+this.width||c.b<this.b||c.b>this.b+this.height?!1:!0};h.prototype.trim=function(){var c=Math.ceil(this.a+this.width),d=Math.floor(this.a),e=Math.ceil(this.b+this.height),m=Math.floor(this.b);this.a=d;this.b=m;this.width=c-d;this.height=e-m};k.prototype.constructor=k;k.prototype.apply=function(c,d){d=
d||new f;var e=c.a,m=c.b;d.a=this.h*e+this.I*m+this.G;d.b=this.m*e+this.J*m+this.H;return d};k.prototype.Nd=function(c){for(var d=0;d<c.length;d++)this.apply(c[d],c[d])};k.prototype.Ac=function(c){var d;d=d||new f;var e=1/(this.h*this.J+this.I*-this.m),m=c.a;c=c.b;d.a=this.J*e*m+-this.I*e*c+(this.H*this.I-this.G*this.J)*e;d.b=this.h*e*c+-this.m*e*m+(-this.H*this.h+this.G*this.m)*e;return d};k.prototype.d=function(c,d){this.G+=c;this.H+=d};k.prototype.scale=function(c,d){this.h*=c;this.J*=d;this.I*=
c;this.m*=d;this.G*=c;this.H*=d;return this};k.prototype.Kd=function(c){var d=this.h,e=this.m,m=this.I,h=this.J;this.h=c.h*d+c.m*m;this.m=c.h*e+c.m*h;this.I=c.I*d+c.J*m;this.J=c.I*e+c.J*h;this.G=c.G*d+c.H*m+this.G;this.H=c.G*e+c.H*h+this.H};k.prototype.c=function(){this.h=1;this.I=this.m=0;this.J=1;this.H=this.G=0};k.prototype.wa=function(){var c=new k;c.h=this.h;c.m=this.m;c.I=this.I;c.J=this.J;c.G=this.G;c.H=this.H;return c};k.c=new k;e.prototype.ka=function(c,d){d=d||!1;for(var e=0,m=this.c.length;e<
m;++e)if(!1===c(this.c[e])||d&&!1===this.c[e].ka(c))return!1};e.prototype.Jb=function(c){for(var d=this.c.length-1;0<=d&&!1!==c(this.c[d]);--d);};e.prototype.nb=function(){this.f=!0};e.prototype.Ma=function(c){this.Na(c)};e.prototype.Na=function(c,d){if(!(c instanceof e))throw Error("child not an Element");c.Pa&&c.Pa.removeChild(c);c.Pa=this;var m=d?this.c.indexOf(d):-1;0<=m?this.c.splice(m,0,c):this.c.push(c)};e.prototype.removeChild=function(c){var d=this.c.indexOf(c);0>d||(this.c.splice(d,1),c.Pa=
!1)};e.prototype.Wc=function(){this.ka(function(c){c.Pa=!1});this.c=[]};C(l,e);C(n,l);C(q,l);q.oc="stage_resize";var m={Oe:function(c){var d=m.Lc(c.width,c.height),e=d.getContext("2d");e.drawImage(c);return e.getImageData(0,0,d.width,d.height)},Lc:function(c,d){var e=document.createElement("canvas");e.width=c;e.height=d;return e},Tb:function(c,d,e){c=m.Lc(c,d);e(c.getContext("2d"));return c}};m.Ce=document.createElement("canvas");m.De=m.Ce.getContext("2d");m.createImageData=function(c,d){return m.De.createImageData(c,
d)};m.Vd=function(c,d){for(var e=Math.round(Math.sqrt(d.length)),h=Math.floor(e/2),f=c.Fb||4,l=c.data,t=c.width,k=c.height,n=Math.ceil(Math.sqrt(t*k/4)),n=m.createImageData(n,n),q=n.data,r=0;r<k;r++)for(var A=0;A<t;A++){for(var x=r,H=A,P=r*t+A,L=0,J=0;J<e;J++)for(var G=0;G<e;G++){var K=x+J-h,E=H+G-h;0<=K&&K<k&&0<=E&&E<t&&(L+=l[(K*t+E)*f]*d[J*e+G])}q[P]=L}return{data:n.data,width:t,height:k,Fb:1}};m.Wd=function(c,d){for(var e=Math.round(Math.sqrt(d.length)),h=Math.floor(e/2),f=c.Fb||4,l=c.data,k=c.width,
n=c.height,q=Math.ceil(Math.sqrt(k*n/4)),q=m.createImageData(q,q),z=q.data,r=0;r<n;r++)for(var A=0;A<k;A++){for(var x=r,H=A,P=r*k+A,L=0,J=0;J<e;J++)for(var G=0;G<e;G++){var K=x+J-h,E=H+G-h;0<=K&&K<n&&0<=E&&E<k&&(L+=(l[(K*k+E)*f]-128)*d[J*e+G])}z[P]=L+128}return{data:q.data,width:k,height:n,Fb:1}};m.Le=function(c,d){for(var e=Math.round(Math.sqrt(d.length)),h=Math.floor(e/2),f=c.data,l=c.width,k=c.height,n=m.createImageData(l,k),q=n.data,z=0;z<k;z++)for(var r=0;r<l;r++){for(var A=z,x=r,H=4*(z*l+r),
P=0,L=0,J=0,G=0;G<e;G++)for(var K=0;K<e;K++){var E=A+G-h,M=x+K-h;0<=E&&E<k&&0<=M&&M<l&&(E=4*(E*l+M),M=d[G*e+K],P+=f[E]*M,L+=f[E+1]*M,J+=f[E+2]*M)}q[H]=P;q[H+1]=L;q[H+2]=J;q[H+3]=255}return n};m.Me=function(c,d){for(var e=Math.round(Math.sqrt(d.length)),h=Math.floor(e/2),f=c.data,l=c.width,k=c.height,n=m.createImageData(l,k),q=n.data,z=0;z<k;z++)for(var r=0;r<l;r++){for(var A=z,x=r,H=4*(z*l+r),P=0,L=0,J=0,G=0;G<e;G++)for(var K=0;K<e;K++){var E=A+G-h,M=x+K-h;0<=E&&E<k&&0<=M&&M<l&&(E=4*(E*l+M),M=d[G*
e+K],P+=(f[E]-128)*M,L+=(f[E+1]-128)*M,J+=(f[E+2]-128)*M)}q[H]=P+128;q[H+1]=L+128;q[H+2]=J+128;q[H+3]=255}return n};c.xd=k;c.nc=f;c.pc=h;c.Ja=l;c.Ad=n;c.sc=q;c.Ka=m})(Q.q);Q.u={};
(function(c){function d(c,d,e){this.l={a:0,b:0};this.Y=0;this.p=c;this.index={a:d,b:e};this.w=null}function f(c,d){this.p=c;this.size=d;this.o=[]}function h(c,e,k,n){function q(c){for(var d={},e=0;e<c.wc.length;e++){var m=c.wc[e],h=m.w.p;d[h]||(d[h]=new f(h,N));h=z[m.p];h.l.a=m.l.a;h.l.b=m.l.b;h.Y=m.Y;A.c(h)}this.la=c.la}function w(d,h){return 0>d||0>h||d>=c||h>=e?-1:h*c+d}function y(){x||(x=z.slice());x.sort(function(c,d){return c.w.o.length<d.w.o.length?1:c.w.o.length>d.w.o.length?-1:c.Y>d.Y?1:
c.Y<d.Y?-1:0});for(var c=0;c<x.length;c++)x[c].Y=c}var t=l("board-data").Uc(this);this.S=!1;this.z=this.W=0;this.i=h.O;var B=!1;c instanceof h&&(B=c.c,this.W=c.W,this.z=c.z,c=B.ta,e=B.ua,k=B.oa,n=B.na);var N={a:k/c,b:n/e},z=[];this.size=N;this.K=null;this.c={ta:c,ua:e,oa:k,na:n,wc:z};for(k=0;k<e;k++)for(n=0;n<c;n++){var r=w(n,k);z[r]=new d(r,n,k)}this.la=0;B&&q.bind(this)(B);if(0==this.la){for(B=0;B<z.length;B++){k=z[B];var A=new f(k.p,N);A.c(k)}this.la=z.length}this.we=function(){for(var c=this.o(),
d={},e=[],m=0;m<c.length;m++){var h=c[m].w;d[h.p]||(d[h.p]=!0,e.push(h))}var c=new ArrayBuffer(18+6*e.length+2*c.length),d=new DataView(c),f=0;d.setUint8(f,2);f+=1;d.setUint8(f,this.c.ta);f+=1;d.setUint8(f,this.c.ua);f+=1;d.setUint16(f,this.c.oa);f+=2;d.setUint16(f,this.c.na);f+=2;d.setUint32(f,this.W);f+=4;d.setUint32(f,this.z);f+=4;d.setUint8(f,this.i);f+=1;d.setUint16(f,e.length);f+=2;for(m=0;m<e.length;++m){var h=e[m],k=h.o[0].l;d.setInt16(f,k.a);f+=2;d.setInt16(f,k.b);f+=2;d.setUint16(f,h.o.length);
f+=2;for(k=0;k<h.o.length;++k)d.setUint16(f,h.o[k].p),f+=2}return c};this.d=function(c){if(c instanceof ArrayBuffer)c=new DataView(c);else if(c.buffer)c=new DataView(c.buffer,c.byteOffset,c.byteLength);else{t.g("unknown format of bytes: "+c);return}var d=0,e=c.getUint8(d),d=d+1;if(1!=e&&2!=e)t.g("cannot init with bytes - wrong format (version: %d)",e);else{if(2==e||3==e)c.getUint8(d),d+=1,c.getUint8(d),d+=1,c.getUint16(d),d+=2,c.getUint16(d),d+=2;this.W=c.getUint32(d);d+=4;this.z=c.getUint32(d);d+=
4;this.i=c.getUint8(d);d+=1;this.la=c.getUint16(d);d+=2;t.e("seed: %d, time: %d",this.W,this.z);for(var m=e=0;m<this.la;++m){for(var h=c.getInt16(d),d=d+2,k=c.getInt16(d),d=d+2,l=null,p=c.getInt16(d),d=d+2,n=0;n<p;++n){var q=c.getUint16(d),d=d+2;l||(l=new f(q,N));z[q].Y=e++;l.c(z[q])}l.o[0].l.a=h;l.o[0].l.b=k;l.Pb(l.o[0],this.S)}}};this.Nc=w;this.Bc=function(c,d,e){var m=z[c];m?(m.l.a=d,m.l.b=e,m.w.Pb(m,this.S),this.K&&this.K.Hc&&this.K.Hc(c,d,e)):t.g("no piece with id: "+c)};this.Md=function(c,d){a=
z[c];b=z[d];a&&b?a==b?t.g("cannot consume join itself (piece)! %d = %d",c,d):a.w==b.w?t.g("cannot consume join itself (group)! %d = %d",c,d):(a.w.o.length>=b.w.o.length?a.w.Dc(b.w,this.S):b.w.Dc(a.w,this.S),this.la--,y(),this.K&&this.K.Gc&&this.K.Gc(c,d)):t.g("no pieces with ids: "+c+", "+d)};this.Ld=function(c){var d=z[c];if(d){for(var d=d.w.o,e=0;e<d.length;e++)d[e].Y=z.length;y();this.K&&this.K.Fc&&this.K.Fc(c)}else t.g("no piece with id: "+c)};this.Od=function(c){this.K&&this.K.Ic&&this.K.Ic(c)};
this.o=function(c){x&&!c||y();return x};this.ea=function(c){return z[c]};var x=!1}function k(){this.c=function(){return(new Date).getTime()}}function e(c,d){function f(c){if(t==c)w.e("state set to same value: "+t);else{c!=n.ub&&N.z();var d=t;t=c;w.e("change state: "+d+" => "+t);y.r(e.$a,t,d)}}function q(c){var d;d=d||1;var e=c.l,f=!1;N.Jc(function(m){if(c==m)return!1;m=m.l;if(!(Math.abs(m.a-e.a)*d>A||Math.abs(m.b-e.b)*d>A))return f=!0,w.e("piece not on top: "+Math.abs(m.a-e.a)+" or "+Math.abs(m.b-
e.b)+" > "+A),!1});f&&w.e("piece not on top");return f}function v(c){function d(e,f){var m=r.Nc(c.index.a+e,c.index.b+f);if((m=r.ea(m))&&c.w!=m.w){var h;h=e*r.size.a/2;var k=f*r.size.b/2,l=c.l.b+k,k=m.l.b-k;h=m.l.a-h-(c.l.a+h);k=k-l;h=h*h+k*k;w.e("%d :: tryConnectPiece: %d (distance: %d, snap: %d)",c.p,m.p,Math.sqrt(h),A);h>A*A||q(m)||N.d(m.p,c.p)}}d(-1,0);d(1,0);d(0,-1);d(0,1)}d=d||!1;var w=l("board").Uc(this),y={r:function(){}};this.j=function(c,d){y.j||(y=new I);y.j(c,d)};this.W=function(){return r.W};
var t=n.Cb;this.i=function(){return t};this.c=new k;var B=0;this.z=function(){if(!r)return!1;var c=this.c.c();if(0==B)B=c;else{var d=c-B;B=c;if(t!=n.C)return r.z;isNaN(d)?w.g("time interval is NaN, %d, %d",B,c):r.z+=d;return r.z}};this.ad=function(){this.z();t==n.Cb&&(this.Gb()?f(n.N):r.i==h.C?f(n.C):0<r.z?f(n.O):f(n.$))};var N=this,z=null;this.ye=function(c){z=c;r&&(r.K=c)};this.Yd=function(){this.z();return r.we()};this.hd=function(d){try{r=new h(c.ta,c.ua,c.oa,c.na),d&&(r.S=[],r.d(d),y.r(e.Za,
r.S)),r.K=z}catch(k){w.g("Error in data: "+k),w.ie(k.stack),f(n.ub)}};var r=null;this.hd(d);var A=0;r&&(A=6+(r.size.a+r.size.b)/16+100);this.re=function(){return c.ta*c.ua};this.Qc=function(){return r.la};this.Gb=function(){return 1==this.Qc()?!0:!1};this.Zc=function(){if(t==n.$||t==n.O)r.i=h.C,f(n.C)};this.oe=function(){t==n.C&&(r.i=h.O,f(n.O))};var x=!1;this.he=function(c){this.Zc();t!=n.C?w.g("grabPiece, but board not active: state="+t):(x&&(y.r(e.Q,"another piece already grabbed: current:"+x+", new:"+
c),this.Vc(x)),r.Ld(c),x=c)};this.Vc=function(c){t!=n.C?w.g("releasePiece, but board not active: state="+t):(r.Od(c),x!=c&&y.r(e.Q,"release wrong piece: current:"+x+", new:"+c),x=!1)};this.ne=function(c,d,f){t!=n.C?w.g("movePiece, but board not active: state="+t):(r.S=[],r.Bc(c,d,f),y.r(e.Za,r.S),r.S=!1,x!=c&&y.r(e.Q,"move wrong piece: current:"+x+", new:"+c))};this.ge=function(){var c=r.Nc(0,0);return r.ea(c)};this.Kb=function(c){for(var d=r.o(),e=0;e<d.length&&!1!==c(d[e]);e++);};this.Jc=function(c){for(var d=
r.o(),e=d.length-1;0<=e&&!1!==c(d[e]);--e);};this.d=function(c,d){t!=n.C?w.g("joinPieces, but board not active: state="+t):(r.Md(c,d),y.r(e.lc),this.Gb()&&f(n.N))};this.Fe=function(c){r.S=[];c=r.ea(c).w;for(var d=0;d<c.o.length;d++)v(c.o[d]);y.r(e.Za,r.S);r.S=!1};this.se=function(){w.e("board.prepareNew");if(t!=n.Cb)w.g("cannot prepare board - state=%d",t);else{var d=Math.sqrt(c.oa*c.na*1.7/12),e=4*d,h=3*d;this.Kb(function(c){var d=Math.round((Math.random()-.5)*e),f=Math.round((Math.random()-.5)*
h);c.Y=Math.random();r.Bc(c.p,d,f)});r.o(!0);f(n.$)}}}var l=Q.log;d.prototype.toString=function(){var c=["id: "+this.p];c.push("index: "+this.index.a+","+this.index.b);c.push("z: "+this.Y);c.push("position: "+this.l.a+","+this.l.b);c.push("group: "+this.w);return c.join(", ")};f.prototype.toString=function(){return this.p+" ["+this.o.length+"]"};f.prototype.c=function(c){c.w=this;this.o.push(c)};f.prototype.Td=function(){for(var c={a:0,b:0},d=0;d<this.o.length;d++){var e=this.o[d];c.a+=e.l.a;c.b+=
e.l.b}c.a/=this.o.length;c.b/=this.o.length;return c};f.prototype.Pb=function(c,d){for(var e=0;e<this.o.length;e++){var f=this.o[e];d&&d.push(f);f!=c&&(f.l.a=c.l.a+this.size.a*(f.index.a-c.index.a),f.l.b=c.l.b+this.size.b*(f.index.b-c.index.b))}};f.prototype.Dc=function(c,d){for(var e=0;e<c.o.length;e++)this.c(c.o[e]);c.o=[];this.Pb(this.o[0],d)};h.O=0;h.C=1;h.c=2;var n={ub:1,Cb:2,$:3,C:4,O:5,N:6},q;for(q in n)n[q]=q;e.Za="pieces_changed";e.$a="state_changed";e.lc="pieces_joined";e.Q="board_error";
for(q in n)e[q]=n[q];c.D=e;c.Ie=h})(Q.u);function ra(c){this.identifier=c;this.qa=null}function T(c){this.A=c;this.vb=this.vb.bind(this);this.Ya=this.Ya.bind(this);this.xb=this.xb.bind(this);this.wb=this.wb.bind(this);this.c={};this.d=null;-1<(" "+c.className+" ").replace(/[\n\t]/g," ").indexOf(" button ")||(c.className+=" button");this.A&&(this.A.addEventListener("mousedown",this.vb,!0),this.A.addEventListener("touchstart",this.xb,!0),this.A.addEventListener("touchend",this.wb,!0))}T.prototype=Object.create(I.prototype);
g=T.prototype;g.constructor=T;function sa(c,d){c.d==c.c[d]&&(c.d=null);delete c.c[d]}function ta(c,d,f,h){c.c[d]||(c.c[d]=new ra(d));!c.d&&h&&(c.d=c.c[d]);d=c.c[d];d==c.d&&(d.qa=f,c.r(d.qa,null))}function ua(c,d,f){c=c.A.getBoundingClientRect();return d<c.left||d>c.right||f<c.top||f>c.bottom?!1:!0}g.xb=function(c){c.preventDefault();for(var d=0;d<c.changedTouches.length;++d)ta(this,c.changedTouches[d].identifier,"down",!0)};
g.wb=function(c){c.preventDefault();for(var d=0;d<c.changedTouches.length;++d){var f=c.changedTouches[d];ta(this,f.identifier,"up");ua(this,f.clientX,f.clientY)&&ta(this,f.identifier,"click");sa(this,f.identifier)}};g.vb=function(c){c.preventDefault();ta(this,"mouse","down",!0);(this.f=this.f||!1)||window.addEventListener("mouseup",this.Ya,!0);this.f=!0};
g.Ya=function(c){window.removeEventListener("mouseup",this.Ya,!0);this.f=!1;c.preventDefault();ta(this,"mouse","up");ua(this,c.clientX,c.clientY)&&ta(this,"mouse","click");sa(this,"mouse")};
function ga(){var c=Q.n.token;function d(c){_fn_error&&_fn_error(c)}function f(){_fn_success&&_fn_success(this)}function h(){k.e("load image: "+e);l.x=new Image;l.x.crossOrigin="";l.x.onload=function(){f.call(l)};l.x.src=e}var k=Q.log("config");this.n=function(){_fn_success=Q.nd};this.g=function(c){_fn_error=c;return this};_fn_success=_fn_error=null;this.f=!1;this.q="";this.d=!0;this.c=!1;this.size={a:0,b:0};var e=this.x=null;this.B=null;var l=this,n=new XMLHttpRequest,q="/ajax/api/2/game_lookup.php";
U&&(q+="?nocors");n.open("POST",q,!0);n.setRequestHeader("Content-type","application/x-www-form-urlencoded");n.send("token="+c);n.onload=function(){var c=JSON.parse(this.response||this.responseText);"OK"!=c.result?(k.g("ERROR: "+this.response),d.call(l,va)):(l.f=c.id,l.size.a=c.x_count,l.size.b=c.y_count,l.q=c.title,l.d=c.effects?!0:!1,l.c=c.timer?!0:!1,e=c.image,l.B=c.progress,h())}}var va="unknown_puzzle";
function wa(){function c(){if(Q.c){var c=Q.c.R.z()/1E3,c=Math.floor(c);if(k!=c&&(k=c,f.gb)){var d;d=new Date(1E3*c);var c=d.getUTCSeconds(),h=d.getUTCMinutes();d=d.getUTCHours();10>c&&(c="0"+c);10>h&&(h="0"+h);f.gb.innerHTML=d+":"+h+":"+c}}}function d(c){if(!Q.c)return!1;c=c.wheelDelta||-c.detail;c=Math.max(-1,Math.min(1,c));Q.c.rb(.5*c);return!1}this.c=!1;this.f=null;Q.j(Q.Ra,function(c){switch(c){case Q.d.O:this.Aa(!0);break;case Q.d.C:case Q.d.$:case Q.d.N:this.Aa(!1)}}.bind(this));Q.j(Q.Je,function(){}.bind(this));
Q.j(Q.Q,function(c){this.ke=c;this.Aa(!0)}.bind(this));this.Ia=0;Q.f.add(function(c,d){Q.c&&0!=this.Ia&&Q.c.rb(.07*this.Ia*d)}.bind(this));window.addEventListener("mousewheel",d.bind(this),!1);window.addEventListener("DOMMouseScroll",d.bind(this),!1);var f=null,h=!1;this.da=function(c){(new T(c)).j("click",function(){Q.pb?Q.exitFullscreen():Q.ld()}.bind(this))};this.Fa=function(c){this.f=c;this.Aa(!0);c=this.d.bind(this);Q.da.j(xa,c);Q.da.j(ya,c)};this.ca=function(c){this.ae=c};this.Qa=function(d){f=
{gb:d};d&&(f.display=d.style.display,setInterval(function(){h&&c()},100))};var k=!1;this.u=function(d){h=d;f.gb&&(d&&c(),f.gb.style.display=d?f.display:"none")};this.qb=function(){if(!this.n){var c=Q.ca?Q.ca.x:null;if(!c)return null;var d=Math.min(300/c.width,250/c.height);this.n=Q.q.Ka.Tb(Math.round(c.width*d),Math.round(c.height*d),function(f){f.scale(d,d);f.drawImage(c,0,0)})}return this.n};this.Aa=function(c){var d={};d.time=Q.c?Q.c.R.z()/1E3:0;d.image=this.qb();d.close=this.d.bind(this);d.error=
this.ke;this.f&&this.f(c?Q.i:null,d);this.c&&Q.da.be();(this.c=c)&&Q.da.de()};this.T=function(){this.c?this.Aa(!1):this.Aa(!0)};this.d=function(c){c=c||"close";if("reconnect"==c)Q.za(),this.Aa(!1);else{switch(Q.i){case Q.d.$:this.T();break;case Q.d.C:Q.c.R.oe();break;case Q.d.O:Q.c.R.Zc();break;case Q.d.N:this.T()}"restart"==c&&this.mb()}};this.mb=function(){var c=Q.td;confirm("If you continue and restart this puzzle your current progress will be lost")&&c()};this.Ha=function(c){(new T(c)).j("click",
this.d.bind(this))};this.Ra=function(c,d){c=new T(c);d=new T(d);var f=this.pb.bind(this);c.j("down",function(){this.q(1)}.bind(this));c.j("up",f);d.j("down",function(){this.q(-1)}.bind(this));d.j("up",f)};this.q=function(c){Q.c&&(this.Ia=.12*c,this.ob=(new Date).getTime(),Q.c.rb(this.Ia))};this.pb=function(){Q.c&&(200>(new Date).getTime()-this.ob&&Q.c.rb(.66*this.Ia),this.Ia=0)}}var S;
function ha(){var c=Q.n.gui;if(!S){var d=new wa;d.Ra(c.plus,c.minus);d.da(c.fullscreen);d.Ha(c.pause);d.Fa(c.fn);d.ca(c.dlg);d.Qa(c.watch);S=d}}function pa(){var c=Q.B.fe();if(S)switch(c){case za:case Aa:case Ba:S.u(!1);break;case Ca:S.u(!0)}}function Da(c){this.identifier=c;this.qa=this.M=null;this.global=new Q.q.nc}var xa="mousedown",ya="touchstart";
function ea(c,d){this.A=c;this.n=d;this.f=!1;this.Mb=this.Mb.bind(this);this.yb=this.yb.bind(this);this.Bb=this.Bb.bind(this);this.Ab=this.Ab.bind(this);this.Ob=this.Ob.bind(this);this.Nb=this.Nb.bind(this);this.zb=this.zb.bind(this);this.A&&!this.f&&(window.document.addEventListener("mousemove",this.Mb,!0),this.A.addEventListener("mousedown",this.yb,!0),this.A.addEventListener("touchstart",this.Bb,!0),this.A.addEventListener("touchend",this.Ab,!0),this.A.addEventListener("touchmove",this.Ob,!0),
this.A.addEventListener("touchcancel",this.Nb,!0),window.addEventListener("mouseup",this.zb,!0),this.f=!0);this.d={};this.c=null}function Ea(c,d,f,h){if(!d.bb&&!d.ba||!d.fb(f))return null;if(d.bb){var k;d.Jb(function(e){if(k=Ea(c,e,f,h))return d.ba&&h(d),!1});if(k)return k}return d.ba?(h(d),d):null}function Fa(c,d,f){f=f||!1;c.d[d]||(c.d[d]=new Da(d));!c.c&&f&&(c.c=c.d[d]);return c.d[d]}function Ga(c,d){c.c==c.d[d]&&(c.c=null);delete c.d[d]}
function Ha(c,d,f,h){var k=c.A.getBoundingClientRect();d.a=c.A.width/k.width*(f-k.left);d.b=c.A.height/k.height*(h-k.top)}function V(c,d,f,h,k,e){var l;l=f+": "+d+" ("+h+","+k+") "+(e?"init":"-")+("; before="+(c.c?c.c.identifier:"-"));var n=Fa(c,d,e||!1);l+="; after="+(c.c?c.c.identifier:"-");"touchmove"!=f&&"mousemove"!=f&&Ia(l);n==c.c&&(n.M=null,n.qa=f,Ha(c,n.global,h,k),Ea(c,c.n,n.global,function(c){n.M||(n.M=c);c.r(n.qa,n)}.bind(c)))}var Ja=[];
function Ia(c){if(!c)return Ja;for(Ja.push((new Date).getTime()+": "+c);10<Ja.length;)Ja.shift()}g=ea.prototype;g.yb=function(c){0==c.button&&(c.preventDefault(),V(this,"mouse",xa,c.clientX,c.clientY,!0))};g.Mb=function(c){c.preventDefault();V(this,"mouse","mousemove",c.clientX,c.clientY)};g.zb=function(c){c.preventDefault();V(this,"mouse","mouseup",c.clientX,c.clientY);Ga(this,"mouse")};
g.Bb=function(c){c.preventDefault();for(var d=0;d<c.changedTouches.length;++d){var f=c.changedTouches[d];V(this,f.identifier,ya,f.clientX,f.clientY,!0)}};g.Ab=function(c){c.preventDefault();for(var d=0;d<c.changedTouches.length;++d){var f=c.changedTouches[d];V(this,f.identifier,"touchend",f.clientX,f.clientY);Ga(this,f.identifier)}};
g.Nb=function(c){c.preventDefault();for(var d=0;d<c.changedTouches.length;++d){var f=c.changedTouches[d];V(this,f.identifier,"touchcancel",f.clientX,f.clientY);Ga(this,f.identifier)}};g.Ob=function(c){c.preventDefault();for(var d=0;d<c.changedTouches.length;++d){var f=c.changedTouches[d];V(this,f.identifier,"touchmove",f.clientX,f.clientY)}};
function Ka(c){function d(){h=!0;for(var c=0;c<this.Sa.length;c++)if(this.Sa[c].i!=W)return;this.i!=W&&this.Sd(this);this.Pc(this);this.i==X&&(this.i=La);if(this.i==Y||this.i==W)f.e("reset()"),this.Yc()}this.data=!1;this.Sd=c;this.M=this.Pc=!1;this.Sa=[];var f=Q.log("recognizer");this.P=function(c){f.e(this+": setState="+c);switch(c){case X:if(this.i!=Ma)return;break;case Y:if(this.i==W)return;break;case W:if(this.i!=Ma)return;break;case La:case Ma:f.g("state: "+c+" cannot be set");default:return}this.i=
c;switch(c){case X:case La:case Ka.c:d.call(this)}};var h=!1;this.Id=function(c){this.data=c;this.u();h=!1;f.e("touchStart()");this.q();h||d.call(this)};this.Hd=function(){h=!1;f.e("touchMove()");this.n();h||d.call(this)};this.Gd=function(){h=!1;f.e("touchEnd()");this.f();h||d.call(this)};this.ve=function(c){c=this.Sa.indexOf(c);0<=c&&this.Sa.splice(c)};this.T=function(c){this.Sa.push(c)};this.u=function(){this.i=Ma};this.Yc=function(){};this.q=function(){};this.n=function(){};this.f=function(){}}
var Ma="possible",X="began",La="changed",Y="ended",W="failed";function Na(c){Ka.call(this,c);this.toString=function(){return"PanRecognizer"};this.q=function(){this.d=!1;this.c={a:0,b:0};this.Ba={a:0,b:0};this.origin=!1;this.origin=this.data.global.wa()};this.n=function(){this.d||(this.d=!0,this.P(X));var c=this.c.a,f=this.c.b;this.c.a=this.data.global.a-this.origin.a;this.c.b=this.data.global.b-this.origin.b;this.Ba.a=this.c.a-c;this.Ba.b=this.c.b-f};this.f=function(){this.d&&this.P(Y)}}
function Oa(c){function d(d){e||(e=!0,c.k.j("mouseup",f).j("touchend",f).j("mousemove",h).j("touchmove",h).j("touchcancel",f));q=d;for(var k=0;k<l.length;k++)l[k].Id(d)}function f(d){e&&(e=!1,c.k.Ga("mouseup",f).Ga("touchend",f).Ga("mousemove",h).Ga("touchmove",h).Ga("touchcancel",f));if(d==q){for(d=0;d<l.length;d++)l[d].i!=W&&l[d].i!=Y&&l[d].Gd();n=q=!1}}function h(c){if(c==q)for(c=0;c<l.length;c++)l[c].i!=W&&l[c].i!=Y&&l[c].Hd()}function k(c){if(!n)switch(c.i){case X:case Y:for(n=c,c=0;c<l.length;c++)l[c]!=
n&&l[c].P(W)}}c.j(xa,d).j(ya,d);var e=!1,l=[],n=!1,q=!1;c.yc=function(d){d.Pc=k;d.M=c;l.push(d)};c.Xc=function(c){var d=l.indexOf(c);0<=d&&l.splice(d,1);for(d=0;d<l.length;d++)l[d].ve(c)}}
function Pa(c,d,f,h){var k=.7;this.M=c;this.ee=Qa;var e={},l={},n=(new Date).getTime(),k=1E3*k,q;for(q in d)e[q]=c[q],l[q]=d[q]-e[q];this.c=function(){var m=((new Date).getTime()-n)/k;1<m&&(m=1);var p=this.ee(m),q;for(q in d)c[q]=e[q]+l[q]*p;f&&f(this);1>m||(h&&h(this),this.Ae())}.bind(this);Q.f.add(this.c);this.Ae=function(){Q.f.ue(this.c)}}function Qa(c){if(.5>c)return c*c*2;c--;return-c*c*2+1}Q.f={};Q.f.V=[];Q.f.Oc=0;Q.f.Eb=!1;Q.f.add=function(c){Q.f.V.push(c);Q.f.Eb||(Q.f.Eb=!0,requestAnimationFrame(Q.f.gd))};
Q.f.ue=function(c){c=Q.f.V.indexOf(c);0<=c&&Q.f.V.splice(c,1)};Q.f.gd=function(c){c=c||(new Date).getTime();var d=c-Q.f.Oc;Q.f.Oc=c;for(var f=Q.f.V.length-1;0<=f;--f)Q.f.V[f](c,d);0<Q.f.V.length?requestAnimationFrame(Q.f.gd):Q.f.Eb=!1};Q.f.Wb=0;window.requestAnimationFrame||(Q.f.Wb=1,window.requestAnimationFrame=window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame);
window.requestAnimationFrame||(Q.f.Wb=2,window.requestAnimationFrame=function(c){setTimeout(c,1E3/60)});window._timerType=Q.f.Wb;
(function(c){function d(c,e){d.X.call(this,e);this.toString=function(){return"PieceDragRecognizer"};var f=!1;this.Ea=null;this.q=function(){this.c={a:0,b:0};this.Ba={a:0,b:0};this.origin=this.data.global.wa();this.Ea=c.pe(this.origin);!this.Ea.ea||15<this.Ea.Oa?this.P(W):f=setTimeout(function(){this.P(X);f=!1}.bind(this),100)};this.Yc=function(){this.d()};this.d=function(){f&&clearTimeout(f);f=!1};this.n=function(){var c=this.c.a,d=this.c.b;this.c.a=this.data.global.a-this.origin.a;this.c.b=this.data.global.b-
this.origin.b;this.Ba.a=this.c.a-c;this.Ba.b=this.c.b-d;this.i==Ma&&(c=this.c.a,d=this.c.b,100>c*c+d*d||(this.P(X),this.d()))};this.f=function(){this.d();this.i!=X&&this.i!=La||this.P(Y)}}function f(c){f.X.call(this);c.j(Q.u.D.Za,function(c){for(var e=0;e<c.length;e++){var f=c[e];d[f.p].ia(f.l.a,f.l.b);d[f.p].fa()}});var d={};this.toString=function(){return"BoardRender"};this.ka=function(e){c.Kb(function(c){if(d[c.p])return e(d[c.p])})};this.Jb=function(e){c.Jc(function(c){if(d[c.p])return e(d[c.p])})};
this.ga=function(c){c.beginPath();c.moveTo(-500,0);c.lineTo(500,0);c.moveTo(0,-500);c.lineTo(0,500);c.strokeStyle="#080";c.stroke()};this.Rd=function(f,k,u){function D(){for(var c=(new Date).getTime(),n=0;0<v.length;){var n=v.shift(),r=new h(n);r.Xd(k,f);r.Vb(1);r.p=n.p;r.ia(n.l.a,n.l.b);d[n.p]=r;B.Ma(r);t+=r.x.width*r.x.height;n=(new Date).getTime()-c;if(30<n)break}y+=n;e.e("work left: "+v.length+", "+y+" ms)");B.r(l.Wa,w-v.length,w);0<v.length?setTimeout(D,0):(B.Dd=y,B.Cd=t,u())}var v=[];c.Kb(function(c){v.push(c)});
var w=v.length,y=0,t=0,B=this;D()}}function h(c){var d,f;function k(c,d){for(var e=0;e<c.length;e++)c[e]*=d}function l(c){var d=(new Date).getTime(),e=d-window.Fd;window.Fd=d;c&&(window["t_"+c]=window["t_"+c]||0,window["t_"+c]+=e)}function D(c,d,e,f){var h=d.qe(e,f);h.a-=2;h.b-=2;h.width+=4;h.height+=4;v.Da(h);var m=-h.a,n=-h.b,q=h.width,x=h.height,D;Q.q.Ka.Tb(q,x,function(c){c.fillStyle="#000000";c.fillRect(0,0,q,x);c.setTransform(1,0,0,1,m,n);c.beginPath();d.Hb(c,e,f);c.closePath();c.fillStyle=
"#FFFFFF";c.fill();var h=[1,1,1,1,1,1,1,1,1],w=[-2,-1,0,-1,0,1,0,1,2];k(h,1/9);k(w,.175);c=c.getImageData(0,0,q,x);l();c=Q.q.Ka.Vd(c,h);l("emboss-norm");c=Q.q.Ka.Wd(c,w);l("emboss-float");D=c.data});l();h=Q.q.Ka.Tb(q,x,function(h){h.save();h.setTransform(1,0,0,1,m,n);h.beginPath();d.Hb(h,e,f);h.closePath();h.fillStyle="#FFFFFF";h.fill();h.globalCompositeOperation="source-atop";h.drawImage(c,(e+.5)*-d.dd(),(f+.5)*-d.ed());for(var k=h.getImageData(0,0,q,x),l=k.data,p=0;p<k.width*k.height;++p)for(var u=
0;3>u;++u){var v=D[p]/256,N=l[4*p+u]/256;.5>v&&(l[4*p+u]=2*v*N*256);.5<v&&(l[4*p+u]=256*(1-2*(1-v)*(1-N)))}h.putImageData(k,0,0);h.restore();h.globalAlpha=.5;h.lineWidth=1;h.strokeStyle="#000";h.stroke()});l("source");return h}h.X.call(this);var v=this;this.toString=function(){return"Piece-"+this.p};this.Xd=function(e,h){d=h.dd();f=h.ed();this.x=D(e,h,c.index.a,c.index.b)};this.ga=function(c){for(var d=this.Da(),e=0;1>e;e++)c.drawImage(this.x,d.a,d.b);Q.Qa&&(c.font="35px Arial",c.fillStyle="#000",
c.fillText(this.p,0,0))};this.ce=function(c){var h=this.Xb(c),k=Math.max(Math.abs(h.a)-d/2,Math.abs(h.b)-f/2);return 0>=k||this.fb(c)&&(c=this.Da(),h.a-=c.a,h.b-=c.b,this.x&&this.x.getContext||(e.g(this.x),e.g(this.x.getContext)),128<this.x.getContext("2d").getImageData(Math.round(h.a),Math.round(h.b),1,1).data[3])?0:k}}function k(c,h,m,p){function u(c){c==Q.u.D.N&&D()}function D(){w.r(l.N);var c=v.ge(),c=c.w.Td();y.ia(-c.a,-c.b);c=w.k.Xb(w.Ee(c));w.ia(c.a,c.b);w.Xc(w.ib);c={a:c.a,b:c.b,$c:w.scale()};
new Pa(c,{a:0,b:0,$c:1},function(c){w.ia(c.M.a,c.M.b);w.Vb(c.M.$c)},function(){w.xc(!0)})}k.X.call(this);var v=new Q.u.D({ta:h,ua:m,oa:c.width,na:c.height},p);this.R=v;this.toString=function(){return"Puzzle"};this.ba=!0;this.bb=!1;Oa(this);this.ib=new d(this,function(c){var d=c.Ea.ea;if(!(2<c.Ea.Oa))switch(c.i){case X:v.he(d.p);this.r(l.yd,d);break;case Y:this.r(l.zd,d);v.Vc(d.p);v.Fe(d.p);d.k.ra();break;case La:var e=c.Ea.le;c=this.ha.Ac(c.data.global.wa());c.sub(e);v.ne(d.p,c.a,c.b);d.k.ra()}}.bind(this));
this.Cc=new Na(function(c){var d=this.l();d.a+=c.Ba.a;d.b+=c.Ba.b;this.ia(d.a,d.b)}.bind(this));this.Cc.T(this.ib);this.yc(this.ib);this.yc(this.Cc);this.toString=function(){return"Puzzle"};var w=this,y=new f(v);this.Ma(y);y.j(l.Wa,function(c,d){w.r(l.Wa,c,d)});this.x=c;this.W=function(){return v.W};setTimeout(function(){if(v.i()==Q.u.D.ub)e.g("board is INVALID");else if(v.Gb())w.Xc(w.ib),w.xc(!1),v.ad(),w.r(l.Va);else{v.j(Q.u.D.$a,u);e.e("cutter:"+c.width+","+c.height+" : "+h+","+m+", seed:"+v.W());
var d=new qa(h,m,c.width,c.height,v.W());y.Rd(d,c,function(){v.ad();w.r(l.Va,y.Dd,y.Cd)})}},0);this.xc=function(c){c=c||!1;e.e("add final image: transition="+c);var d=new Q.q.Ad;d.ze(this.x);this.Ma(d);c&&(d.Ub(0),new Pa({h:0},{h:1},function(c){d.Ub(c.M.h)}.bind(this),function(){this.removeChild(y)}.bind(this)))};this.rb=function(c){c=this.scale()*(1+c/3);this.xe(new Q.q.nc(0,0),c)};this.xe=function(c,d){d=Math.max(.25,Math.min(d,2));var e=this.scale();this.Vb(d);e=this.scale()/e;c.a-=this.l().a;
c.b-=this.l().b;c.a*=1-e;c.b*=1-e;e=this.l();e.a+=c.a;e.b+=c.b;this.ia(e.a,e.b);this.k.fa()};this.ga=function(c){c.beginPath();c.moveTo(-200,0);c.lineTo(200,0);c.moveTo(0,-200);c.lineTo(0,200);c.strokeStyle="#f00";c.stroke()};this.pe=function(c){var d={Oa:0,ea:null};y.Jb(function(e){var h=e.ce(c);if(!d.ea||h<d.Oa)if(d.ea=e,d.Oa=h,0>=h)return!1});d.le=d.ea.Xb(c);return d};this.fb=function(){return!0}}var e=Q.log("puzzle");C(d,Ka);C(f,Q.q.Ja);C(h,Q.q.Ja);var l={yd:"piece_start_drag",zd:"piece_end_drag",
Ke:"pieces_will_join",N:"complete",Wa:"build_progress",Va:"build_complete"};C(k,Q.q.Ja);c.kd=k;c.Fa=l})(Q);function ma(c){var d=S,f=Q.log("dialog");d.ae(c,{qa:"completion",aa:function(){f.e("dialog closed")}})}var U=window.XDomainRequest?!0:!1;function Ra(c){for(var d="",f=0;f<c.length;f++)d+=String.fromCharCode(c[f]);return btoa(d)}function Sa(c){c=atob(c);for(var d=new ArrayBuffer(c.length),f=new Uint8Array(d),h=0;h<c.length;h++)f[h]=c.charCodeAt(h);return d}
function Ta(c){var d=new O(c.length+1);d.ja(98);d.Zb(c);return d.data()}
function ia(c){function d(c){y!=c&&(y=c,p.r(ja,p,c))}function f(c){var d=Ia(),d=d?d.join("\n"):"-";r.L(new Z.fc(c+"\n"+d))}function h(c){m.e("boardStateChange:"+c);switch(c){case Q.u.D.C:r.L(new Z.rc);break;case Q.u.D.O:r.L(new Z.mc);break;case Q.u.D.N:r.db()}}function k(c,h){if(c)m.g("handleMasterResponse: "+c),m.g("permanent error: "+u),y==Ua&&d(oa);else for(var f=0;f<h.length;f++){var k=h[f];m.e("Progress::processMessage [master]: "+k);k instanceof Z.gc&&(u=k.ma,m.e("progress game key: "+u),D.push(k.kb),
D.push(k.lb),e())}}function e(){if(0==D.length)m.g("No game servers available");else{var c=D[0];r=null;switch(c.split("/")[0].toLowerCase()){case "http:":case "https:":r=new Va(c);break;case "ws:":case "wss:":r=new Wa(c)}r?(r.d(u),r.f(q),r.c(n),r.L(new Z.ic),r.db()):(m.g("unknown server"),l())}}function l(){D.shift();setTimeout(e,0)}function n(c,e){m.g("game-error: "+c+", "+e);switch(c){case "close":if(y==Ua){l();break}p.r(la,e);d(Xa);break;case "unsupported":l()}}function q(c){m.e("Progress::processMessage [game]: "+
c);c instanceof Z.uc&&(v=null,w=c.eb,1==c.B?m.e("progress available, wait for sync message"):2==c.B?m.e("game is complete"):(m.e("Progress (no progress): INITIALIZED / CONNECTED"),d(na)));c instanceof Z.tc&&(v=c.va,p.c?(m.e("Got SYNC from server, updating board"),p.c.R.hd(c.va),d(na)):y!=Ua?m.g("not initializing but no puzzle"):(m.e("Progress (progress available): INITIALIZED / CONNECTED"),d(na)));c instanceof Z.ec&&(c=JSON.parse(c.jb),c.message&&0<c.message.length&&p.r(ka,c.message))}var m=Q.log("progress"),
p=this,u=!1,D=[],v=null,w=za,y=Ua;this.Qd=function(){return v};this.fe=function(){return w};setTimeout(function(){m.e("token:"+c);c?(z.L(new Z.sb(c,!1)),z.c(k)):d(oa)},0);this.aa=function(){r&&r.aa()};this.c=null;this.Pd=function(){var c=Q.c;m.e("assignPuzzle: "+c+", state="+y);y!=oa&&(this.c=c,this.c.R.ye(this),this.c.R.j(Q.u.D.$a,h),this.c.R.j(Q.u.D.Q,f))};this.Zd=function(){z.L(new Z.sb(c,!0));z.c(function(c,d){if(c)m.g("unable to detach game");else for(var e=0;e<d.length;e++)m.e("Progress::processMessage [master]: "+
d[e]);window.location.reload()})};this.Gc=function(c,d){m.e("dataJoinPieces: "+c+", "+d);r.L(new Z.jc(c,d))};var t=!1,B=!1;this.Fc=function(c){m.e("dataGrabPiece: "+c);t=c;r.L(new Z.hc(c))};this.Ic=function(c){m.e("dataReleasePiece: "+c);B&&r.L(new Z.kc(c,B.a,B.b));B=!1;r.L(new Z.qc(c))};this.Hc=function(c,d,e){c!=t?m.g("dataMovePiece: wrong piece! currentPiece="+t):(B||(B={a:0,b:0}),B.a=d,B.b=e)};var N="https://progress.jigidi.com";Q.n.progressServer&&(N=Q.n.progressServer);var z=new Ya(N+"/master");
z.d(function(){return new Z.Xa(Q.Ha)});var r=null;this.za=function(){e()}}ia.prototype=Object.create(I.prototype);ia.prototype.constructor=ia;var Ua="initializing",na="connected",Xa="disconnected",oa="unavailable",ja="state_change",ka="completion_message",la="disconnect",za=0,Aa=1,Ca=2,Ba=3;
function Ya(c){function d(c,d){if(d){d.v&&(d=[d]);for(var e=0;e<d.length;e++)Z.Ua(c,d[e])}}function f(c,d,e){var f=null;try{h.e("open: "+c);f=U?new XDomainRequest:new XMLHttpRequest;f.open("POST",c,!0);var k=d.data();U?(k="t"+Ra(k),f.responseType="text"):(f.responseType="arraybuffer",k=Ta(k));f.send(k)}catch(v){h.g("exception: "+v+", description: "+v.description);e(v,null);return}f.onload=function(){var f=this.response||this.responseText;n=l=!1;var k=this.status;if(400<=k)e("error-code:"+k,null);
else{U&&(f=Sa(f));h.e(c+": bytes sent: "+d.l()+", bytes received: "+f.byteLength);var y=[];Z.Qb(f,function(c){y.push(c)})||e("error in stream",null);e(null,y)}};f.onerror=function(c){h.g("send error: "+c);n=!1;e(c,null)}}var h=Q.log("master-connection");this.L=function(c){e.push(c)};this.d=function(c){k=c};var k=!1,e=[],l=null,n=!1;this.c=function(q){if(1>e.length&&!l)setTimeout(function(){q(null,[])});else if(n)h.e("send-queue: skip - transmission already in progress");else{n=!0;l?h.g("send-queue: retrying ... # of new messages: "+
e.length):l=new O;var m=l;1<=e.length&&(0==m.l()&&k&&d(l,k()),d(m,e),e=[]);new f(c,m,q)}}}
function Va(c){function d(c){if(l)for(var d=0;d<c.length;d++){var f=c[d];e.e("HttpConnection::received: "+f);l(f)}else e.g("no message-handler assigned to connection")}function f(c){if(1>n.length)setTimeout(function(){c([])});else{var d=new O;q&&Z.Ua(d,q);m&&Z.Ua(d,m);for(var f=0;f<n.length;f++){var k=n[f];e.e("msg: "+k);Z.Ua(d,k)}u.push({Be:d,t:c});n=[];h()}}function h(){if(!D&&0!=u.length){D=!0;var d=u[0];new k(c,d.Be,function(c,e){c?D=!1:(d.t(e),u.shift(),D=!1,h())})}}function k(c,d,f){var h=[];
try{oReq=U?new XDomainRequest:new XMLHttpRequest;oReq.open("POST",c,!0);var k=d.data();U?(k="t"+Ra(k),oReq.responseType="text"):(oReq.responseType="arraybuffer",k=Ta(k));oReq.send(k)}catch(l){e.g("exception: "+l),f(l,null)}oReq.onload=function(){var k=this.response||this.responseText;U&&(k=Sa(k));e.e(c+": bytes sent: "+d.l()+", bytes received: "+k.byteLength);Z.Qb(k,function(c){h.push(c)});f(null,h)};oReq.onerror=function(c){e.g("send error: "+c);f(c,null)}}var e=Q.log("http-connection"),l=null,n=
[],q=null,m=null;e.e("using http-connection: "+c);this.d=function(c){game_key=c;q=new Z.tb(game_key);m=new Z.Xa(Q.Ha)};this.f=function(c){l=c};this.c=function(){};this.aa=function(){p&&clearInterval(p);p=!1};this.L=function(c){n.push(c)};this.db=function(){f(d)};var p=setInterval(this.db,5E3),u=[],D=!1}
function Wa(c){function d(c){if(q){var d=new O;Z.Ua(d,c);m.send(d.data())}else f.g("not connected, can't send: "+c)}var f=Q.log("ws-connection"),h=null,k=null,e=[],l=null,n=null,q=!1;this.d=function(c){game_key=c;l=new Z.tb(game_key);n=new Z.Xa(Q.Ha);this.L(l);this.L(n)};this.f=function(c){h=c};this.c=function(c){k=c};this.aa=function(){};this.L=function(c){e?(f.e("queueMessage: "+c),e.push(c)):(f.e("postMessage: "+c),d(c))};this.db=function(){};var m=null;setTimeout(function(){f.e("connecting: "+
c);"WebSocket"in window?(m=new WebSocket(c,["jgdp"]),m.binaryType="arraybuffer",m.onopen=function(){f.e("connected");q=!0;var c=e;for(e=null;msg=c.shift();)d(msg)},m.onclose=function(c){var d=c.code,e=c.reason;f.e("WebSocket close:",d,e);1006==d&&(e="jcc,close-abnormal,reconnect");var h=c=!1,l=[];if(e)for(var e=e.split(","),m=0;m<e.length;m++)"jcc"==e[m]?c=!0:"reconnect"==e[m]?h=!0:l.push(e[m]);e={za:!1,cb:"code-"+d};c&&(e.za=h,e.cb=l.join(","));q=!1;k&&k("close",e)},m.onerror=function(c){q=!1;f.g("WebSocket Error "+
c);k&&k("socket-error",c)},m.onmessage=function(c){c=c.data;c instanceof ArrayBuffer&&Z.Qb(c,function(c){h(c)})}):k&&k("unsupported",void 0)},0)}var Z={};
(function(c){Q.log("protocol");var d=Uint8Array,f={};O.prototype.xa=function(){for(var c=this.Sc(),c=new Uint8Array(c),d="",e=0;e<c.length;){var f=c[e++];if(127<f){if(191<f&&224>f){if(e>=c.length)throw"UTF-8 decode: incomplete 2-byte sequence";f=(f&31)<<6|c[e]&63}else if(223<f&&240>f){if(e+1>=c.length)throw"UTF-8 decode: incomplete 3-byte sequence";f=(f&15)<<12|(c[e]&63)<<6|c[++e]&63}else if(239<f&&248>f){if(e+2>=c.length)throw"UTF-8 decode: incomplete 4-byte sequence";f=(f&7)<<18|(c[e]&63)<<12|(c[++e]&
63)<<6|c[++e]&63}else throw"UTF-8 decode: unknown multibyte start 0x"+f.toString(16)+" at index "+(e-1);++e}if(65535>=f)d+=String.fromCharCode(f);else if(1114111>=f)f-=65536,d+=String.fromCharCode(f>>10|55296),d+=String.fromCharCode(f&1023|56320);else throw"UTF-8 decode: code point 0x"+f.toString(16)+" exceeds UTF-16 reach";}return d};O.prototype.Ca=function(c){for(var f=0,e=new d(4*c.length),l=0;l!=c.length;l++){var n=c.charCodeAt(l);if(128>n)e[f++]=n;else{if(2048>n)e[f++]=n>>6|192;else{if(55295<
n&&56320>n){if(++l==c.length)throw"UTF-8 encode: incomplete surrogate pair";var q=c.charCodeAt(l);if(56320>q||57343<q)throw"UTF-8 encode: second char code 0x"+q.toString(16)+" at index "+l+" in surrogate pair out of range";n=65536+((n&1023)<<10)+(q&1023);e[f++]=n>>18|240;e[f++]=n>>12&63|128}else e[f++]=n>>12|224;e[f++]=n>>6&63|128}e[f++]=n&63|128}}if(e.slice)c=e.slice(0,f);else if(e.subarray)c=e.subarray(0,f);else throw Error("not way to slice data");this.jd(c)};c.F=function(d,k){c[k.name]=k;f[d]=
k;k.prototype.vc=d};c.me=function(c){return f[c]?new f[c]:!1};c.Ge=function(c){return null==c.vc?!1:c.vc};c.Qb=function(d,f){for(d=new O(d);0<d.c();){var e=null;try{var l=d.ya();if(e=c.me(l))e.y(d);else throw Error("invalid event: "+l);}catch(n){return R.g("error in stream: "+n),!1}if(e&&!1===f(e))return!1}return!0};c.Ua=function(d,f){var e=c.Ge(f);!1!==e&&(d.ja(e),f.v(d))};c.sb=function(c,d){this.d=c;this.c=d||0;this.y=function(c){this.d=c.xa();this.c=c.ya()};this.v=function(c){c.Ca(this.d);c.ja(this.c)};
this.toString=function(){return"FindGame: "+this.d+", create: "+this.c}};c.gc=function(c,d,e){this.kb=c;this.lb=d;this.ma=e;this.y=function(c){this.kb=c.xa();this.lb=c.xa();this.ma=c.xa()};this.v=function(c){c.Ca(this.kb);c.Ca(this.lb);c.Ca(this.ma)};this.toString=function(){return"GameInfo: server= "+this.kb+" / "+this.lb+", key="+this.ma}};c.od=function(){this.c=this.data=null;this.y=function(c){1==c.ya()&&(this.c={ta:c.ya(),ua:c.ya(),oa:c.pa(),na:c.pa()})};this.v=function(c){this.c?(c.ja(1),c.ja(this.c.ta),
c.ja(this.c.ua),c.sa(this.c.oa),c.sa(this.c.na)):c.ja(0);this.data&&c.Zb(this.data)};this.toString=function(){return"Events"}};c.Xa=function(c){this.c=c;this.y=function(c){this.c=c.pa()};this.v=function(c){c.$b(this.c)};this.toString=function(){return"ClientVersion: "+this.c}};c.tb=function(c){this.ma=c;this.y=function(c){this.ma=c.xa()};this.v=function(c){c.Ca(this.ma)};this.toString=function(){return"GameKey: "+this.ma}};c.fc=function(c){this.message=c;this.y=function(c){this.message=c.xa()};this.v=
function(c){c.Ca(this.message)};this.toString=function(){return"Debug: "+this.message}};c.ic=function(){this.y=function(){};this.v=function(){};this.toString=function(){return"Hello"}};c.Bd=function(c){this.z=c;this.y=function(c){this.z=c.te()};this.v=function(c){c.He(this.z)};this.toString=function(){return"Time: "+this.z}};c.kc=function(c,d,e){this.index=c;this.a=Math.round(d);this.b=Math.round(e);this.y=function(c){this.index=c.pa();this.a=c.Tc();this.b=c.Tc()};this.v=function(c){c.sa(this.index);
c.$b(this.a);c.$b(this.b)};this.toString=function(){return"Move: ["+this.index+"] "+this.a+","+this.b}};c.jc=function(c,d){this.M=c;this.c=d;this.y=function(c){this.M=c.pa();this.c=c.pa()};this.v=function(c){c.sa(this.M);c.sa(this.c)};this.toString=function(){return"Join: "+this.M+","+this.c}};c.mc=function(){this.y=function(){};this.v=function(){};this.toString=function(){return"Pause"}};c.rc=function(){this.y=function(){};this.v=function(){};this.toString=function(){return"Resume"}};c.hc=function(c){this.index=
c;this.y=function(c){this.index=c.pa()};this.v=function(c){c.sa(this.index)};this.toString=function(){return"Grab: "+this.index}};c.qc=function(c){this.index=c;this.y=function(c){this.index=c.pa()};this.v=function(c){c.sa(this.index)};this.toString=function(){return"Release: "+this.index}};c.ec=function(c){this.jb=c;this.y=function(c){this.jb=c.xa()};this.v=function(c){c.Ca(this.jb)};this.toString=function(){return"Complete: "+this.jb}};c.tc=function(c){this.va=c;this.y=function(c){this.va=c.Sc()};
this.v=function(c){c.jd(this.va)};this.toString=function(){return"Sync: "+(this.va.length?this.va.length:this.va.byteLength)+" bytes"}};c.uc=function(c,d){this.B=d;this.eb=c;this.y=function(c){this.eb=c.ya();this.B=c.ya()};this.v=function(c){c.ja(this.eb);c.ja(this.B)};this.toString=function(){return"welcome: type="+this.eb+", progress="+this.B}};c.F(1,c.sb);c.F(2,c.gc);c.F(3,c.tb);c.F(4,c.ic);c.F(5,c.uc);c.F(6,c.tc);c.F(7,c.hc);c.F(8,c.qc);c.F(9,c.kc);c.F(10,c.jc);c.F(11,c.Bd);c.F(12,c.mc);c.F(13,
c.rc);c.F(14,c.ec);c.F(15,c.Xa);c.F(32,c.od);c.F(33,c.fc)})(Z);
function fa(){function c(){var c=f.k.size.width-20,d=f.k.size.height-20,c=new Q.q.pc(-c/2,-d/2,c,d);f.Da(c)}Q.q.Ja.call(this);var d=Q.log("cover");this.toString=function(){return"Cover"};this.ba=!1;this.bb=!0;Oa(this);var f=this;this.Ub(.4);var h=0;this.de=function(){this.ba||(this.ba=!0,c(),this.fa(),0!=h&&d.e("cover.enable - refCount not 0: "+h));h++};this.be=function(){h--;0<h||(0!=h&&d.e("cover.disable - refCount not 0: "+h),this.ba=!1,this.fa())};this.zc=function(){c();this.k.j(Q.q.sc.oc,c)};
this.ga=function(){}}fa.prototype=Object.create(Q.q.Ja.prototype);fa.prototype.constructor=fa;
(function(){function c(c,d){for(var e=0;e<c.length;e++)(new T(c[e])).j("click",d)}function d(){if(!m){m={};for(var d=document.getElementById("menu_items"),e=0;e<d.children.length;e++){var h=d.children[e];c(h.getElementsByClassName("replay"),function(){u.close()});c(h.getElementsByClassName("restart"),function(){u.close("restart")});c(h.getElementsByClassName("reconnect"),function(){u.close("reconnect")});c(h.getElementsByClassName("dlg_close"),function(){this.parentElement.Lb()}.bind(h));m[h.id]=
h}d.parentNode.removeChild(d);n=document.getElementById("menu");q=document.createElement("div");q.className="cover";(new T(q)).j("click",f)}}function f(){n.lastChild.firstChild.Ec()}function h(c){var d=document.createElement("div");d.className="center";var e=document.createElement("div");e.Db=d;e.aa=null;e.ab=!1;e.Ed=c||!1;d.appendChild(e);e.className="panel";e.cd=function(){if(!this.ab){this.ab=!0;this.Ed?n.insertBefore(this.Db,n.firstChild):n.appendChild(this.Db);p++;q.parentNode&&n.removeChild(q);
n.insertBefore(q,n.lastChild);n.style.display="block";var c=this.clientHeight;this.style.left=Math.round(-this.clientWidth/2)+"px";this.style.top=Math.round(-c/2)+"px"}};e.Ec=function(){this.Lb()};e.Lb=function(){this.ab&&(this.aa&&this.aa(),this.ab=!1,n.removeChild(this.Db),p--,q.parentNode&&n.removeChild(q),n.insertBefore(q,n.lastChild),0<p||(n.removeChild(q),n.style.display="none"))};return e}function k(e){d();if(!D&&e.image){D=!0;c([m.mi_close],function(){u.close()});var f;f=m.mi_preview.getElementsByClassName("preview");
for(var h=0;h<f.length;h++)f[h].appendChild(e.image);f=m.mi_colors.getElementsByClassName("swatch");c(f,function(){var c=window.getComputedStyle(this.A,null).getPropertyValue("background-color");Q.ud(c)})}}function e(c,e){template=e.qa||"dialog";d();var f=h();l.e("panel: "+f);f.aa=e.aa;var k=m[template];switch(template){case "completion":k.getElementsByClassName("content")[0].innerHTML=c.replace(/\n/g,"<br>").replace(/\r/g,"")}f.appendChild(k);f.cd()}var l=Q.log("ui"),n=null,q=null,m=null,p=0,u=null,
D=!1,v=null;Q.ob({gui:{fn:function(c,d){k(d);u=d;v&&v.Lb();v=null;if(c){var e={};e[Q.d.La]="loading";e[Q.d.$]="mi_preview,mi_colors,mi_restart,mi_close";e[Q.d.O]="mi_preview,mi_timer,mi_colors,mi_restart,mi_close";e[Q.d.N]="mi_timer,mi_colors,mi_restart,mi_close";e[Q.d.Q]="error";v=h(!0);v.Ec=d.close;for(var e=e[c].split(","),f=0;f<e.length;++f){var n=e[f],p=m[n];if(p){switch(n){case "mi_timer":var n=p.getElementsByClassName("time")[0],q=d.time,q=new Date(1E3*q),A=q.getUTCSeconds(),x=q.getUTCMinutes(),
q=q.getUTCHours();10>A&&(A="0"+A);10>x&&(x="0"+x);n.innerHTML=q+":"+x+":"+A;break;case "error":p.getElementsByTagName("span")[0].innerHTML=d.error}v.appendChild(p)}else l.g("no item with id: "+n)}v.cd()}},dlg:e}});e(null,{qa:"warning"})})();})();
//# sourceMappingURL=http://localhost.jigidi.com/js/build/jigidi-compiled.map
